// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krcyvmmpylqxzkboxmib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyY3l2bW1weWxxeHprYm94bWliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MTEwODYsImV4cCI6MjA2MzI4NzA4Nn0.CR7IPb2pjvMjTb7T-OO97woZpIqjgYkJPPUjd6Lr1Lg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);